### PR TITLE
Add news item for the virtual workshop

### PR DESCRIPTION
**Pull request by jameshclrk**
Will add in more details, such as dates, etc before merging.

### CODE REVIEW

**Comment by jameshclrk** [comment]
I was going to wait and post this when we had the new date, I think the email said it should be sent out within the next day.

**Comment by nb-epcc** [comment]
That works for me. Thanks! :)

**Comment by jameshclrk** [comment]
I addressed your other comments and put a placeholder everywhere I saw November 15th.

I'll swap the date in as soon as we hear 😄

**Comment by nb-epcc** [comment]
Fab, thanks @jameshclrk ! :)

**Pull request merged**
